// <auto-generated />
using CursoNetCoreQualyteam.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CursoNetCoreQualyteam.Migrations
{
    [DbContext(typeof(ReceitasContext))]
    [Migration("20190726154558_SeedReceitasFake")]
    partial class SeedReceitasFake
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CursoNetCoreQualyteam.Dominio.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("Ingredientes");

                    b.Property<string>("Preparacao");

                    b.Property<string>("Titulo");

                    b.Property<string>("UrlDaImagem");

                    b.HasKey("Id");

                    b.ToTable("Receitas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Um belo prato de feijão com arroz.",
                            Ingredientes = "Feijão, Arroz",
                            Preparacao = "Misture.",
                            Titulo = "Feijão com Arroz",
                            UrlDaImagem = "rec.com/fjar"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Uma porção de batata",
                            Ingredientes = "Batata, Óleo, Sal",
                            Preparacao = "Frite a bata",
                            Titulo = "Batatas Fritas",
                            UrlDaImagem = "rec.com/btfr"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
