// <auto-generated />
using System;
using CursoNetCoreQualyteam.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CursoNetCoreQualyteam.Migrations
{
    [DbContext(typeof(ReceitasContext))]
    partial class ReceitasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CursoNetCoreQualyteam.Dominio.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Ingredientes");

                    b.Property<string>("Preparacao");

                    b.Property<string>("Titulo");

                    b.Property<string>("UrlDaImagem");

                    b.HasKey("Id");

                    b.ToTable("Receitas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e52f21f0-72d6-4066-84c3-99359c2b3216"),
                            Descricao = "Um belo prato de feijão com arroz.",
                            Ingredientes = "Feijão, Arroz",
                            Preparacao = "Misture.",
                            Titulo = "Feijão com Arroz",
                            UrlDaImagem = "rec.com/fjar"
                        },
                        new
                        {
                            Id = new Guid("7c76d64e-3524-4a0b-b0f2-79c6b22ff47a"),
                            Descricao = "Uma porção de batata",
                            Ingredientes = "Batata, Óleo, Sal",
                            Preparacao = "Frite a bata",
                            Titulo = "Batatas Fritas",
                            UrlDaImagem = "rec.com/btfr"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
